import { Plant, ButterflyRecord } from '../types';

const now = new Date().toISOString();

export const samplePlants: Plant[] = [
  {
    id: 'plant-001',
    x: 600,
    y: 550,
    name: '馬纓丹',
    species: 'Lantana camara',
    variety: '黃花品種',
    plantDate: '2024-03-15',
    quantity: 5,
    photos: [],
    notes: '蜜源植物，吸引多種蝴蝶',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plant-002',
    x: 800,
    y: 450,
    name: '冇骨消',
    species: 'Sambucus chinensis',
    variety: '',
    plantDate: '2024-03-20',
    quantity: 3,
    photos: [],
    notes: '鳳蝶幼蟲寄主植物',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plant-003',
    x: 500,
    y: 700,
    name: '繁星花',
    species: 'Pentas lanceolata',
    variety: '紅花品種',
    plantDate: '2024-04-01',
    quantity: 10,
    photos: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plant-004',
    x: 1000,
    y: 650,
    name: '柑橘',
    species: 'Citrus reticulata',
    variety: '',
    plantDate: '2023-06-10',
    quantity: 2,
    photos: [],
    notes: '鳳蝶幼蟲寄主植物',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plant-005',
    x: 1200,
    y: 500,
    name: '金露花',
    species: 'Duranta erecta',
    variety: '',
    plantDate: '2024-05-12',
    quantity: 4,
    photos: [],
    notes: '蜜源植物',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plant-006',
    x: 900,
    y: 800,
    name: '蝴蝶菊',
    species: 'Wedelia chinensis',
    variety: '',
    plantDate: '2024-02-28',
    quantity: 8,
    photos: [],
    notes: '地被蜜源植物',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plant-007',
    x: 1300,
    y: 750,
    name: '大花咸豐草',
    species: 'Bidens pilosa',
    variety: '',
    plantDate: '2024-01-01',
    quantity: 20,
    photos: [],
    notes: '野生蜜源',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'plant-008',
    x: 700,
    y: 900,
    name: '薜荔',
    species: 'Ficus pumila',
    variety: '',
    plantDate: '2023-09-01',
    quantity: 3,
    photos: [],
    notes: '榕屬植物，紫斑蝶寄主',
    createdAt: now,
    updatedAt: now,
  },
];

export const sampleRecords: ButterflyRecord[] = [
  {
    id: 'rec-001',
    plantId: 'plant-001',
    type: 'egg',
    species: '大鳳蝶',
    date: '2025-06-01',
    quantity: 8,
    photos: [],
    instar: 0,
    expectedEmerge: '',
    notes: '發現於葉背',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rec-002',
    plantId: 'plant-001',
    type: 'larva',
    species: '大鳳蝶',
    date: '2025-06-05',
    quantity: 3,
    photos: [],
    instar: 3,
    expectedEmerge: '',
    notes: '已達三齡',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rec-003',
    plantId: 'plant-002',
    type: 'egg',
    species: '青斑鳳蝶',
    date: '2025-05-20',
    quantity: 5,
    photos: [],
    instar: 0,
    expectedEmerge: '',
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rec-004',
    plantId: 'plant-002',
    type: 'pupa',
    species: '青斑鳳蝶',
    date: '2025-06-10',
    quantity: 1,
    photos: [],
    instar: 0,
    expectedEmerge: '2025-06-25',
    notes: '懸掛於枝條下方',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'rec-005',
    plantId: 'plant-004',
    type: 'larva',
    species: '無尾鳳蝶',
    date: '2025-06-03',
    quantity: 2,
    photos: [],
    instar: 2,
    expectedEmerge: '',
    notes: '正在取食嫩葉',
    createdAt: now,
    updatedAt: now,
  },
];

export function loadSampleData(): { plants: Plant[]; butterflyRecords: ButterflyRecord[] } {
  return { plants: samplePlants, butterflyRecords: sampleRecords };
}